"""initial schema

Revision ID: b3627699c66f
Revises: 
Create Date: 2026-05-19 12:23:33.544643

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3627699c66f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('total_achievements', sa.Integer(), nullable=False),
    sa.Column('total_gamerscore', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_title_id'), 'games', ['title_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xuid', sa.String(length=50), nullable=False),
    sa.Column('gamertag', sa.String(length=100), nullable=False),
    sa.Column('gamerscore', sa.Integer(), nullable=False),
    sa.Column('account_tier', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_xuid'), 'users', ['xuid'], unique=True)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('locked_description', sa.String(length=1000), nullable=True),
    sa.Column('gamerscore_value', sa.Integer(), nullable=False),
    sa.Column('rarity_percent', sa.Float(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'achievement_id', name='uq_achievement_per_game')
    )
    op.create_index(op.f('ix_achievements_game_id'), 'achievements', ['game_id'], unique=False)
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('current_gamerscore', sa.Integer(), nullable=False),
    sa.Column('current_achievements_unlocked', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game')
    )
    op.create_index(op.f('ix_user_games_game_id'), 'user_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_user_games_user_id'), 'user_games', ['user_id'], unique=False)
    op.create_table('unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_unlock')
    )
    op.create_index(op.f('ix_unlocks_achievement_id'), 'unlocks', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_unlocks_user_id'), 'unlocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unlocks_user_id'), table_name='unlocks')
    op.drop_index(op.f('ix_unlocks_achievement_id'), table_name='unlocks')
    op.drop_table('unlocks')
    op.drop_index(op.f('ix_user_games_user_id'), table_name='user_games')
    op.drop_index(op.f('ix_user_games_game_id'), table_name='user_games')
    op.drop_table('user_games')
    op.drop_index(op.f('ix_achievements_game_id'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_xuid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_title_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
